### PR TITLE
Changes to better sync with the mkiocccentry repo

### PR DESCRIPTION
**Pull request by lcn2**
If MKIOCCCENTRY_USE is defined, then code will compile as if it was
under the mkiocccentry repo:

    https://github.com/ioccc-src/mkiocccentry

These changes sync with mkiocccentry's iocccsize v28.8 2022-02-20.
In particular, the following files are after applying these
mkiocccentry repo commits:

    mkiocccentry commit 407979f97257b0093c900cd4697d35ce897c979a
    mkiocccentry commit a50f486f68301cf1d16035a2896ae825afd4dc61
    mkiocccentry commit 59bc18cf550b5471a74d153f9e3fb496008df515
    mkiocccentry commit d5d46d506aa447adabc8e72f8929a9c85b58b369
    mkiocccentry commit e35269401d6bbe4825895ac7e1367c5b18a13bb8
    mkiocccentry commit 8786f03538cda741f5fe59cabedc3f464e982936

and the following files in this pull request will be identical
in both repos.

    iocccsize-test.sh
    iocccsize.c
    iocccsize.h
    iocccsize_err.h
    rule_count.c

While the default for DIGRAPHS and TRIGRAPHS remains defined (true)
as far as iocccsize.h, in this pull request, code was added to
iocccsize-test.sh and detect if there exists limit_ioccc.sh.  The
iocccsize-test.sh has been modified to test if DIGRAPHS and/or
TRIGRAPHS are defined.  The Digraph and Trigraph tests now work
both with and without DIGRAPHS / TRIGRAPHS being defined.

The test directory used by iocccsize-test.sh was changed from
test to test-iocccsize.  This is consistent with mkiocccentry repo
where a number of tools have their own test-xxx directory.

The iocccsize-test.sh script will exit 0 if all is well,
or exit 1 if at least 1 test failed.

The err.h file was renamed iocccsize_err.h.

The iocccsize_err.h include file was modified so that if iocccsize
is compiled with dbg.c and dbg.h (and linked with dbg.o), then the
mkiocccentry error, warning and debug facility is used.  In this
pull request, no dbg.c nor dbg.h is supplied.  The makefile does
not link with dbg.o.  Unless MKIOCCCENTRY_USE is defined, dbg.h is
not included.

In order to avoid name space conflicts, the code uses the following
function name:

    iocccsize_warnx(...)
    iocccsize_errx(ex, ...)
    iocccsize_dbg(level, ...)

The iocccsize_err.h, if MKIOCCCENTRY_USE is defined translates those
iocccsize_xxx() functions into mkiocccentry error, warning and debug
facility.  If MKIOCCCENTRY_USE is not defined, then those iocccsize_xxx()
functions are translated into portable fprintf() and fputc() calls.

Removed macros for unused error, warning and debug calls.

The iocccsize command line is now:

	usage: iocccsize [-h] [-i] [-v level] [-V] prog.c
	usage: iocccsize [-h] [-i] [-v level] [-V] < prog.c

	-i		ignored for backward compatibility
	-h		print usage message in stderr and exit 2
	-v level	set debug level (def: none)
	-V		print version and exit 3

The iocccsize -v command line flag was changed to "-v level" in order
to be consistent with all of the other mkiocccentry tools.

By default,the Rule 2b count is written to stdout.
If the debug level is > 0, then the Rule 2a, Rule 2b,
and keyword count is written to stdout instead.

Moved the rule_count() function set was moved from iocccsize.c
into a new rule_count.c file.  This is to allow the mkiocccentry
repo to call the rule_count() function directly.

The iocccsize tool no longer writes its input to output.
The iocccsize-test.sh no longer assumes the source file
will be written to stdout.  The stand-alone iocccsize now
only prints Rule 2b size by default.

The iocccsize-test.sh no longer prints 'Nothing to be done for'
lines during the test.

The rule_count() function, unless the '-v level' is given on
the command line, does not print anything.  This is consistent
with how mkiocccentry tools uses the rule_count() function.

Broke up the usage message string into two parts in order
to be compatible with C compilers that do not support string
constants longer than 511 characters.

Exit codes have been changed to:

	0 - source code is within Rule 2a and Rule 2b limits
	1 - source code larger than Rule 2a and/or Rule 2b limits
	2 - -h used and help printed
	3 - -V used and version printed
	4 - invalid command line
	>= 5 - some internal error occurred

The usage message documents these exit codes.

Updated README.md to reflect the new usage message.

Updated the Rule 2a constant (was MAX_SIZE. now RULE_2A_SIZE), and
the Rule 2b constant (was MAX_COUNT, now RULE_2B_SIZE) to be
consistent with the values from limit_ioccc.h in the mkiocccentry
repo.  If MKIOCCCENTRY_USE is defined, then limit_ioccc.h (not
included in this repo) defines will cause RULE_2A_SIZE and RULE_2B_SIZE
values from limit_ioccc.h to be used instead.

The word buffer size was expanded to 256.

The RuleCount typedef includes warning booleans used by
the mkiocccentry tool.  The iocccsize.c code will issue
warnings (via iocccsize_warnx()) accordingly.

The iocccsize version, by default is "unofficial iocccsize version".
When compiled with MKIOCCCENTRY_USE, the iocccsize version
takes on the version defined by the mkiocccentry repo.

Fixed a case where some user's system did not correctly
reopen stdin as the file argument stream.  The iocccsize.c
now does an fopen() on the file argument and passes that stream
to setvbuf() and rule_count().

Added /*ooo*/ to support the seqcexit tool.

Fixed use of non-standard %zu format.

While the makefile is not part of the mkiocccentry repo,
we added a clobber rule as a alias for distclean.
Added a ${WERROR} to make is easy to compile with -Werror
(however the default remains to not use -Werror),
The make distclean clobber rule removed macOS *.dSYM cruft.

In order to compile on several system platforms, including macOS,
we had to comment out the #${PROJ}$E rule lines and instead
use a iocccsize rule to compile.  These lines are marked with:

    # XXX - gross hack - fix me - XXX

Without those lines, for example, macOS would fail to make.
For example, the original makefile would fail as follows:

    $ make distclean all
    rm -f iocccsize.i iocccsize.o *.stackdump *.core 2>/dev/null
    rm -fr iocccsize test a.out VERSION 2>/dev/null
    cc -g -std=c11 -Wall -Wextra -Wno-char-subscripts -pedantic  -DWITH_MAIN -o .c
    clang: error: no input files
    make: *** [iocccsize] Error 1

Fixed various typos and hopefully did not add many more.  :-)

### CODE REVIEW

**Comment by lcn2** [comment]
Expect a followup pull request to address some minor compiler portability and testing issues we discovered.

**Comment by lcn2** [comment]
Updated pull request:

Changes to better sync with the mkiocccentry repo #2

These changes sync with mkiocccentry's iocccsize v28.9 2022-02-23.

Fixed a number if shellcheck discovered issues (portability and shell
script safety related).

Corrected a problem where iocccsize-test.sh in non-verbose mode
failed on some platforms.

Changed -v to -v level to be compatible with mkiocccentry repo use.

Fixed and updated the usage message.

Added -h option to iocccsize-test.sh to print help / usage message.

Documented iocccsize-test.sh exit codes.

Added -V to be compatible with mkiocccentry repo use.

Avoided problematic C symbols that start with __.

Minor comment and whitespace cleanup.

**Comment by SirWumpus** [comment]
Whoa.   Lots to digest and I think I'll be addressing the above in multiple comments as we discuss.  I can't accept the Pull Request as a whole, since I have some concerns.

First a simple one:

`%zu` does appear in `C11` standard onwards, not sure about C99 since I only have C89, C11, and C2x draft (2019) to check against.  I am assuming `iocccsize` and related tools will be built with current compilers that default to current (or current-1) standard.  How far back are we to maintain standard compatibility?  While C89 is great milestone over K&R, I think C11 should be the minimum now and that the code should avoid as much history (technical debt) cruft.  As the tools move forward, maybe git tag the commit / version where minimum support changes, rather than try be all-in-one for all time.

**Comment by SirWumpus** [comment]
Is it your intent to change Rule 2b from 2053 to 2503 for the next contest?

**Comment by lcn2** [comment]
> Is it your intent to change Rule 2b from 2053 to 2503 for the next contest?

Yes, 2053 ==> 2503.

**Comment by lcn2** [comment]
> Whoa. Lots to digest and I think I'll be addressing the above in multiple comments as we discuss. I can't accept the Pull Request as a whole, since I have some concerns.
> 
> First a simple one:
> 
> `%zu` does appear in `C11` standard onwards, not sure about C99 since I only have C89, C11, and C2x draft (2019) to check against. I am assuming `iocccsize` and related tools will be built with current compilers that default to current (or current-1) standard. How far back are we to maintain standard compatibility? While C89 is great milestone over K&R, I think C11 should be the minimum now and that the code should avoid as much history (technical debt) cruft. As the tools move forward, maybe git tag the commit / version where minimum support changes, rather than try be all-in-one for all time.

As for `%zu`, due to problems with implementations that we encountered, we switched away from its use.

Please understand that we are proving you with this pull request as a courtesy: to help you understand the differences between our official code base and your repo.  

You might consider, applying it to this alternate non-master branch.  Alternately you might wish to clone the [mkiocccentry](https://github.com/ioccc-src/mkiocccentry) repo and just track that if you wish.

If you are not interested in there pull requests, let us know.  It is not our intent to bother you with code changes you might not be interested in.

Thanks again for the `iocccsize` concept!

**Comment by SirWumpus** [comment]
I've accepted the majority of the changes, but reimplemented many.  I think you'll approve.  You should see an updated branch tonight or tomorrow.

**Comment by lcn2** [comment]
Thanks, we will be happy to look at the result.  Let us known when it is ready by adding a comment to this pull request, if you please.

**Comment by lcn2** [comment]
You are free to accept or reject the pull request, of course, as you wish.  While some of the items you mention in [the comment above](https://github.com/SirWumpus/iocccsize/pull/3#issuecomment-1052903003) are interesting, enough of differences won't be implemented in our [mkiocccentry](https://github.com/ioccc-src/mkiocccentry) repo so as to not warrant a further merge.

We will keep a diff should there be a further need to sync later on.

Thanks again and best wishes.

**Pull request closed without merging**
